version: 2

defaults: &defaults
  working_directory: ~/retranslate
  docker:
    - image: circleci/node:10.6-browsers

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
      - run:
          name: Collect coverage
          command: npm run coverage
      - run:
          name: Send coverage to coveralls
          command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only: master

####################################
machine:
  node:
    version: 8.9.4

test:
  override:
    - npm test && npm run build
  post:
    - npm run coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

deployment:
  npm:
    branch: master
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - ./node_modules/.bin/publish
